#!/bin/bash
# SCRIPT THAT REMOVES LINES WITH LESS THAN 2 COLUMNS IN A CSV FILE

# DEFINITION OF THE INPUT FILE PATH
INPUT_CSV="/home/ubuntu/APGL_projet/docs/data.csv"

# CREATES A TEMPORARY FILE
TEMP_FILE=$(mktemp)

# REMOVES LINES WITH LESS THAN 2 COLUMNS
awk -F';' 'NF==2' "$INPUT_CSV" > "$TEMP_FILE"

# MOVES THE TEMPORARY FILE TO THE INPUT FILE
mv "$TEMP_FILE" "$INPUT_CSV"